name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd cricket-devops-dashboard || git clone https://github.com/Vasavi-18/cricket-devops-dashboard.git
            cd cricket-devops-dashboard
            git pull origin main
            docker stop cricket-dashboard || true
            docker rm cricket-dashboard || true
            docker build -t cricket-dashboard .
            docker run -d -p 80:80 --name cricket-dashboard cricket-dashboard